Revert "SELinuxMMAC unit tests"
Broken build.

frameworks/base/services/tests/servicestests/src/com/android/server/pm/SELinuxMMACTests.java:89: error: constructor PackageParser in class PackageParser cannot be applied to given types;
        PackageParser packageParser = new PackageParser(archiveFilePath);
                                      ^
  required: no arguments
  found: String
  reason: actual and formal argument lists differ in length
frameworks/base/services/tests/servicestests/src/com/android/server/pm/SELinuxMMACTests.java:93: error: method parsePackage in class PackageParser cannot be applied to given types;
        PackageParser.Package pkg = packageParser.parsePackage(sourceFile,
                                                 ^
  required: File,int
  found: File,String,DisplayMetrics,int
  reason: actual and formal argument lists differ in length
frameworks/base/services/tests/servicestests/src/com/android/server/pm/SELinuxMMACTests.java:99: error: incompatible types
        boolean savedCerts = packageParser.collectCertificates(pkg, 0);
                                                              ^
  required: boolean
  found:    void
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
make: *** [out/target/common/obj/APPS/FrameworksServicesTests_intermediates/classes-full-debug.jar] Error 41

This reverts commit e6f9bb93f6308581013246a5f5748bf0ecb23444.

Change-Id: I0aa992d7b9eccce7e38c430a8a96084a6ee99866