Revert "Fix vulnerability in MemoryIntArray"
This reverts commit 29f385436b6cb73a9e33b899806b2e2e3c37b093.


BROKE BUILD (as shown in some treehugger builds)

frameworks/base/core/java/android/util/MemoryIntArray.java:84: error: cannot find symbol
        mCloseGuard.open("close");
        ^
        
       
bug:33039926
bug:33042690

Change-Id: Ief875e543ec849fe55c747fb1ed5253f0cd9a122