Revert "[TouchLatency] Update style of touch latency"
This reverts commit 25e88dd1d310a77ec1dba01066fbce133ae0dc7e.

Reason for revert: Build error with Android Studio:
ERROR: /frameworks/base/tests/TouchLatency/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml:1630: AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

Change-Id: I16091f405475a57156a4d62b7dad0853530ab81d