Fix -Wformat
frameworks/base/tools/aapt2/trace/TraceBuffer.cpp:85:51: error: format specifies type 'int' but the argument has type 'pid_t' (aka 'long long') [-Werror,-Wformat]

This is to unblock the ongoing clang update to r596125.

Bug: 472333761
Test: presubmit
Flag: EXEMPT PURE_REFACTOR
Change-Id: Id29632308990b0835ccaf9750d2b886ac9a90ddd