OutOfMemoryError: print Parcel size
OOM can be caused by many reasons. Print the exact
parcel size, as this is all the information
at this layer.

This helps because:
- it makes clear OOM is from this exact throw.
- if the Parcel size is small, it hints to
  a server side issue that leads to OOM.

Bug: 404210068
Test: create OOM, check logs and see error message
Change-Id: I4129ae29f546d60ffbcfd30058bf899b43fa8541