Workaround for javac compilation issue of lambda code
Since ag/32554459 some Robolectric tests are compiling
framework code with javac. For reasons unclear so far this
code fails to compile with javac:

> ShortcutService.java:408: error: variable ri might not have been initialized

https://android-build.googleplex.com/builds/submitted/3416256/angelfish-userdebug/latest/logs

Removing the lambda expressions corrects the issue.

(cherry picked from commit cd49dbd6b5606ebfb4fe1c9e41c97f0d94eb6f89)

BUG: 32554459
Test: m
Change-Id: I189c8ef02dc93b46ef6418c1ff14f2312097898a