Fix std::unique_ptr error with incomplete CommonFeatureGroup
After upgrading libc++, Clang fails to compile DumpManifest.cpp.

prebuilts/clang/host/linux-x86/clang-r498229/include/c++/v1/__memory/unique_ptr.h:63:19: error: invalid application of 'sizeof' to an incomplete type 'aapt::CommonFeatureGroup'
    static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
                  ^~~~~~~~~~~

Fix the problem by deferring the instantiation of ~unique_ptr, by
making the ManifestExtractor constructor out-of-line and moving it and
the initialization of commonFeatureGroup_ to a point after
CommonFeatureGroup has been defined.

Bug: b/175635923
Test: treehugger
(cherry picked from https://googleplex-android-review.googlesource.com/q/commit:896cb8e0209d60eb1d705ee145f51e40fe8b8cf1)
Merged-In: I9ab51f29724fded24773344aa36763ffeea02d00
Change-Id: I9ab51f29724fded24773344aa36763ffeea02d00