Add StorageManager.convert() check earlier in the stack so the command fails early instead of crashing system later.
Bug: 393614518
Flag: EXEMPT BUGFIX
Test: PackageInstallerServiceTest
Test: new error Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Invalid volumeUuid value in session params: ../../../data
	at com.android.server.am.ActiveServices$$ExternalSyntheticThrowBlockOutline3.m(R8$$SyntheticClass:0)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:1045)
        ...

Change-Id: Ifbd9c37565eae47d85ab3198b7bf76fe15a20b4f