Fix framework side of #7132432 com.android.vending:...
...java.lang.IllegalStateException: Can not perform this action
after onSaveInstanceStateat android.support.v4.app.FragmentManagerImpl
.checkStateLoss(FragmentManager.java:1300)

Framework fragment manager also needs to be told its state is not
saved earlier.

Change-Id: Ie5bb327fca6208f7eea6146a1b3223c61c9ecef6